DROP TABLE IF EXISTS contributions CASCADE;
CREATE TABLE contributions (
  id SERIAL PRIMARY KEY NOT NULL,
  contribution VARCHAR NOT NULL,
  stories_id INTEGER REFERENCES stories(id) ON DELETE CASCADE
);
